"""empty message

Revision ID: 02bc99659347
Revises: 8ee3ad833018
Create Date: 2020-01-28 22:20:33.758523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bc99659347'
down_revision = '8ee3ad833018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    # ### end Alembic commands ###
