"""empty message

Revision ID: 185d5e2bf0ff
Revises: 
Create Date: 2020-02-01 17:56:50.139398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185d5e2bf0ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('user_username', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('user_username', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image')
    op.drop_table('todo')
    op.drop_table('user')
    # ### end Alembic commands ###
