"""empty message

Revision ID: 4247832e44cd
Revises: ef04210703a4
Create Date: 2020-02-02 06:52:58.849462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4247832e44cd'
down_revision = 'ef04210703a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_img_title_user', 'user_image', ['title', 'user_username'])
    op.drop_index('title', table_name='user_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'user_image', ['title'], unique=True)
    op.drop_constraint('unique_img_title_user', 'user_image', type_='unique')
    # ### end Alembic commands ###
