"""empty message

Revision ID: 4950b2e4b9a2
Revises: 
Create Date: 2021-02-19 20:58:17.218835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4950b2e4b9a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('user_username', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('user_username', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('title', 'user_username', name='unique_img_title_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image')
    op.drop_table('todo')
    op.drop_table('user')
    # ### end Alembic commands ###
