"""empty message

Revision ID: 4a24fad636f7
Revises: 
Create Date: 2020-02-26 23:31:38.567024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a24fad636f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('bankaccount_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('bankaccount_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('name2', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('last_name2', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('ping', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ad',
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('buyorsell', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('min_limit', sa.Integer(), nullable=False),
    sa.Column('max_limit', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.String(length=10), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('picture', sa.String(length=10), nullable=False),
    sa.Column('isavailable', sa.Boolean(), nullable=False),
    sa.Column('ad_amount', sa.Integer(), nullable=False),
    sa.Column('user_id1', sa.Integer(), nullable=False),
    sa.Column('user_id2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id1'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id2'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('ad_id')
    )
    op.create_table('bank',
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('bank_id')
    )
    op.create_table('ad_bank',
    sa.Column('adbank_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ad.ad_id'], ),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.bank_id'], ),
    sa.PrimaryKeyConstraint('adbank_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_bank')
    op.drop_table('bank')
    op.drop_table('ad')
    op.drop_table('user')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
