"""empty message

Revision ID: a64f8a8b45c4
Revises: 4247832e44cd
Create Date: 2020-09-30 18:39:24.565722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64f8a8b45c4'
down_revision = '4247832e44cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_image', sa.Column('public_id', sa.String(length=500), nullable=False))
    op.create_unique_constraint(None, 'user_image', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_image', type_='unique')
    op.drop_column('user_image', 'public_id')
    # ### end Alembic commands ###
